* manjaro
** pros
- less bloat
** cons
- not officially supported unity editor (works flawless either way)

* install
- git
- git lfs
- docker
  pamac build docker
- dotnet
  pamac build dotnet-sdk-bin
  pamca build dotnet-sdk-3.1
  > we need 3.1 sdk for cos stuff
- mono
  pamac build mono

  if you do not use arch you will need to google and follow install
  instructions

* install unity editor
- make ssh keys, add them to gitlab
- clone gitlab idlegame repo

- get unity hub
  pamac buld unityhub

** specific unity version
- find the version you need
#+begin_src shell
    cd <repo-root>
    cat IdleGame/ProjectSettings/ProjectVersion.txt | head -n 1 | cut  -d " " -f2
#+end_src
- go here https://unity3d.com/get-unity/download/archive
- get the url from the "unity hub" button (e.g. right click "copy link
  address"
#+begin_src shell
  unityhub <link>
#+end_src
- if unity hub mime type is setup correctly you should be able to
  click (I just didn't bother with it because it's a 1 time click)

** git lfs

- **Important** pull after you installed git lfs
  (git pull should be sufficient)

#+begin_src shell
  cd `git rev-parse --show-toplevel`
  git lfs fetch && git lfs pull
#+end_src

** open unity with style (ditch unity hub for the most part)


#+begin_src shell
  sudo ln -s <unity-install-path>/Editor/Unity /usr/bin/unity-editor
#+end_src

make a script

#+begin_src shell
  #!/bin/sh
  unity-editor -forcefree -buildTarget standalone -projectPath <project-path>
#+end_src

project-path is the directory with the sln file.

Now you do not need to click in the hub ever again like some normie.
Also see [[file:unity/.local/bin/unity/unity-open][file:unity/.local/bin/unity/unity-open]]


** unity project symlinks (if you want 2 unities)

#+begin_src shell
  man ln
#+end_src


* IMPROTANT csc patch (without it you get compile errs)

!! without this you cannot compile unity !!

use

`IdleGame/patch_csc_linux.sh`

with 1 arg, the "Data" dir in your unity install. For example `/opt/unity/2019.4.16f1/Editor/Data`

probably something like /home/your-user/unityhub/2019.4.16f1/Editor/Data
if you have some default install.

Hint: check in unityhub for installs to get your install path.


* uri scheme for connecting to twitch
you need this if you want to connect to twitch with browser flow

- script idlegame-auth-handler in your path

> *Important* make sure idlegame-auth-handler is executable

#+begin_src shell
#!/bin/sh
[ "$1" = "-v" ] && echo idlegame-auth-handler version 0.1 && exit 0

echo "$@" >> /tmp/auth-handler-res

mkdir -p /tmp/cos_redirect/ && echo "$@" >> /tmp/cos_redirect/url.txt
zenity --info --text "$@"
#+end_src

#+begin_src
idlegame-auth-handler foo
#+end_src

this should show a window saying foo


- install a .desktop file in `~/.local/share/applications`

#+begin_src shell
  echo "" > ~/.local/share/applications/cos-handler.desktop
  $EDITOR ~/.local/share/applications/cos-handler.desktop
#+end_src

insert this content:

#+begin_src Conf[Desktop]
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
Exec=idlegame-auth-handler %u
TryExec=idlegame-auth-handler
Name=idlegame auth handler
Terminal=false
StartupNotify=false
MimeType=x-scheme-handler/clashofstreamers
#+end_src

- add an entry here ~/.config/mimeapps.list

#+begin_src
x-scheme-handler/clashofstreamers=cos-handler.desktop
#+end_src

I added this line to the bottom of [Default Applications].
Probably does not matter where.

The mimeapps list makes xdg-open look up the desktop file, which says
what program to run.

If it works this should call our script with the url as data.

#+begin_src shell
  xdg-open clashofstreamers://fooo
#+end_src


It then pops a little dialog window with zentiy.

** troubleshoot

you might need to run
#+begin_src
update-desktop-database $HOME/.local/share/applications
#+end_src


* editor
choose
- pycharm (recommended for beginners if you code python)
- doom emacs (good for python, used by some people already, vim bindings)
- spacemacs (vim bindings, similar to doom, more features and more
  users, less minimalistic)
- vscode, intellij (works out of the box)
- https://github.com/SystemCrafters/rational-emacs similar style to
  doom but more bare bones to default emacs (which is good)
- mememacs - ascend with me into space. A config not made to be among
  the stars, but to touch them. By being simple, powerful and focused.

* other software
- gnu stow for dotfile management
- vim as fallback editor
- qutebrowser for a keyboard driven browser
- flameshot for screenshots
- todo: screencast software
- there is cli tools for creating jira tickets, might be a sick booster for testers
  jirazzz

* tips
- do not install program python packages on your system level,
use pyenv for that (pycharm does it auto)
- pamac bulid `python-package-name` for stuff you need on your system only


* cos attachments s3 bucket share ("sharex" bucket)

- install aws cli
  pamac build aws-cli-v2

** 1 script to upload to s3

   [[file:scripts/.local/bin/scripts/s3-cos-attch-upload::export AWS_ACCESS_KEY_ID][upload-file]]

   check
   [[file:scripts/.local/bin/scripts/cos-s3-upload-latest][file:scripts/.local/bin/scripts/cos-s3-upload-latest]]

** screen capture

[[file:scripts/.local/bin/scripts/video-selected][file:scripts/.local/bin/scripts/video-selected]]

- depends on `slop`
#+begin_src
pamac build slop-git
#+end_src

modify to your desire.


** walkthrough make video selected (screen capture)

- bind `video-selected` to a keybind, probably with your wm (eg. KDE plasma)
- hello I selected (see vid) (showcase)
- second invoke of the script finishes the current recording
  [[https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/ben/6219cca7-6358-45ac-877a-7e4c9aa6b153-box-220708-1137-33.mp4]]

- call `s3-cos-attch-upload` on the file
- you can of course make a version that does that auto
- if you desire similar screencaptures
  search for `dmenurecord`

- I use /tmp/recordingpid to show "recording" in my wms modeline.
  as long as /tmp/recordingpid exists, you are recording
  example: [[file:stumpwm/.stumpwm.d/init.lisp]]


** aws profile
you can pass --profile to the aws cli.
Less secure because you have permanent tokens on a plain file on your system.

- in ~/.aws/config
#+begin_src conf
[sharex]
region = eu-central-1
#+end_src

- in ~/.aws/credentials
#+begin_src conf
[sharex]
aws_access_key_id=UUUUUUUUUUUUUUUUUUUU
aws_secret_access_key=uuuuUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
#+end_src

* troubleshoot

** unity hub closes instant
- invoke unity hub via the command line to get the errors
  (general tip anyway)
- There is some bug when it tries to update,
  update or reinstall with pacman (or pamac)

** “connection interrupted” in your browser
caused by docker
maybe this helps https://success.mirantis.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet

* notes
** at the time of writing I did not make airtest recording work
honestly don't really know why you want it
code your airtest with the repl running instead to have instant feedback, ask Ben to set it up


* prefab merge tool (only if you work with prefabs)

[mergetool “unityyamlmerge”] trustExitCode = false cmd = <unity-install-path>Unity-2019.2.8f1/Editor/Data/Tools/UnityYAMLMerge merge -h -p “$BASE” “$REMOTE” “$LOCAL” “$MERGED”


* xsessions
https://wiki.archlinux.org/title/Display_manager#Session_configuration

/usr/share/xsessions/

#+begin_quote
To add/remove entries to your display manager's session list; create/remove the .desktop files in /usr/share/xsessions/ as desired.
#+end_quote

For context your display manager is the login screen.

ctrl + alt + f1...f8 : switch to another tty
7 is usually the "graphical one"

You can also switch to another tty and start your window manager from
there (for trying out).
You login and it starts xterm, then you can startx (if not already
running somewhere).

what I do is I use this:
https://aur.archlinux.org/packages/xinit-xsession

and I start stumpwm in my ~/.xinitrc
This way the only thing I need to worry about is ~/.xinitrc.

It is easy to make a mistake and your window manager wont start.
Do not panic.
Go to another tty and fix the files with a terminal editor.
Common mistakes
- some path is wrong and the program does not exist
- you accidentally do not start a window manager
- you have a script that starts you window manager and it is not executable
Follow the documentation of the wm you like to try + the above linked
arch wiki page.
