(("default" . ((user-emacs-directory . "~/.emacs-mememacs.d")
                (straight-p . t)))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs-spacemacs.d")
               (straight-p . t)))
 ("ambrevar" . ((user-emacs-directory . ".emacs-ambrevar.d")))
 ("doom" . ((user-emacs-directory . ".emacs-doom.d")
            (straight-p . t)
            (env . (("DOOMDIR" . "~/doom-config"))))))
